services:
  pethouseApi:
    image: pethouse
    build:
      context: .
      dockerfile: PethouseAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    command: dotnet ef database update
    depends_on:
      - pethouseDB
  pethouseDB:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Pass1q2w3e..'
    ports:
      - '1433:1433'