services:
  pethouseApi:
    image: pethouseapi
    build:
      context: .
      dockerfile: PethouseAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_RUNNING_IN_CONTAINER: true
      ASPNETCORE_URLS: http://*:8080
    ports:
      - "8080:8080"
    depends_on:
      - pethouseDB
  pethouseDB:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Pass1q2w3e..'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
  pethouseClient:
    image: pethouseclient
    build:
      context: ./PethouseClient
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - client_code:/app
      - client_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  sqlserver_data:
  client_code:
  client_modules:
