services:
  api:
    image: pethouseapi
    build:
      context: .
      dockerfile: PethouseAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_RUNNING_IN_CONTAINER: true
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - db_data:/dev/shm
    environment:
      POSTGRES_PASSWORD: Pass1q2w3e..
      POSTGRES_USER: PetAdmin
      POSTGRES_DB: Pethouse
#  db:
#    image: mcr.microsoft.com/mssql/server
#    environment:
#      ACCEPT_EULA: 'Y'
#      MSSQL_SA_PASSWORD: 'Pass1q2w3e..'
#    volumes:
#      - sqlserver_data:/var/opt/mssql
  client:
    image: pethouseclient
    build:
      context: ./PethouseClient
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./PethouseClient:/app # Maps local directory to container directory.
      - /app/node_modules     # Anonymous volume to avoid node_modules conflicts.
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  db_data:
