services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  api:
    image: pethouseapi
    build:
      context: .
      dockerfile: PethouseAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_RUNNING_IN_CONTAINER: true
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  client:
    image: pethouseclient
    build:
      context: ./PethouseClient
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./PethouseClient:/app # Maps local directory to container directory.
      - /app/node_modules     # Anonymous volume to avoid node_modules conflicts.
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  db_data:
