# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "D:\\DEV\\Net Core\\Pethouse"
      dockerfile: "PethouseAPI/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/PethouseAPI.dll"
    environment: {}
    image: "pethouseapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\BritoPC\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\DEV\\Net Core\\Pethouse\\PethouseAPI:/app:rw"
    - "D:\\DEV\\Net Core\\Pethouse:/src:rw"
    working_dir: "/app"
