# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  pethouseApi:
    build:
      context: "D:\\DEV\\Net Core\\PethouseAPI"
      dockerfile: "PethouseAPI/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/PethouseAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    image: "pethouse:dev"
    ports: []
    volumes:
    - "C:\\Users\\BritoPC\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\DEV\\Net Core\\PethouseAPI\\PethouseAPI:/app:rw"
    - "D:\\DEV\\Net Core\\PethouseAPI:/src:rw"
    working_dir: "/app"
