// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PethouseAPI.Data;

#nullable disable

namespace PethouseAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PethouseAPI.Data.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CarnetCheked")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("MedicalChecked")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("isTOSAppointmentDocumentSigned")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentType = "Hospedaje",
                            CarnetCheked = true,
                            EndDate = new DateOnly(2022, 12, 10),
                            MedicalChecked = true,
                            StartDate = new DateOnly(2022, 10, 10),
                            isTOSAppointmentDocumentSigned = true
                        });
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.BreedSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceLowSeason")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePeakSeason")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BreedSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "0-10kg",
                            Name = "Small",
                            PriceLowSeason = 120.00m,
                            PricePeakSeason = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            Label = "11-25kg",
                            Name = "Medium",
                            PriceLowSeason = 170.00m,
                            PricePeakSeason = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            Label = "26-40kg",
                            Name = "Large",
                            PriceLowSeason = 220.00m,
                            PricePeakSeason = 200.00m
                        },
                        new
                        {
                            Id = 4,
                            Label = "41-60kg",
                            Name = "Extra Large",
                            PriceLowSeason = 270.00m,
                            PricePeakSeason = 250.00m
                        });
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "calle falsa 123",
                            Email = "coco@gmail.com",
                            EmergencyContactName = "Dai",
                            EmergencyContactPhone = "9992923923",
                            EmergencyContactRelationship = "Sister",
                            Name = "Juan Brito",
                            PhoneNumber = "9992923563"
                        },
                        new
                        {
                            Id = 2,
                            Address = "calle falsa 123",
                            Email = "dai@gmail.com",
                            EmergencyContactName = "coco",
                            EmergencyContactPhone = "111111111",
                            EmergencyContactRelationship = "brother",
                            Name = "Dai",
                            PhoneNumber = "99999999"
                        });
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.PeakSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PeakSeasons");
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BreedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BreedSizeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool>("IsMedicated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedSizeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreedName = "Chihuahua",
                            BreedSizeId = 1,
                            DateOfBirth = new DateOnly(2022, 10, 10),
                            IsMedicated = false,
                            Name = "Pocha",
                            Notes = "None",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            BreedName = "Border",
                            BreedSizeId = 2,
                            DateOfBirth = new DateOnly(2020, 10, 10),
                            IsMedicated = false,
                            Name = "Luna",
                            Notes = "None",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            BreedName = "Labrador",
                            BreedSizeId = 3,
                            DateOfBirth = new DateOnly(2018, 10, 10),
                            IsMedicated = false,
                            Name = "Coco",
                            Notes = "None",
                            OwnerId = 2
                        });
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.PetAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PetId");

                    b.ToTable("PetAppointments");
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.Pet", b =>
                {
                    b.HasOne("PethouseAPI.Data.Models.BreedSize", "BreedSize")
                        .WithMany("Pets")
                        .HasForeignKey("BreedSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PethouseAPI.Data.Models.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreedSize");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.PetAppointment", b =>
                {
                    b.HasOne("PethouseAPI.Data.Models.Appointment", "Appointment")
                        .WithMany("PetsAppointments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PethouseAPI.Data.Models.Pet", "Pet")
                        .WithMany("PetsAppointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.Appointment", b =>
                {
                    b.Navigation("PetsAppointments");
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.BreedSize", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PethouseAPI.Data.Models.Pet", b =>
                {
                    b.Navigation("PetsAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
